select
    event.event_id,
    event.job_id,
    event.session_id,
    event.turn_id,
    event.emitted_at,
    json_extract_string(claim.value, '$.claim_id') as claim_id,
    json_extract_string(claim.value, '$.canonical_supplier_id') as canonical_supplier_id,
    json_extract_string(claim.value, '$.observed_supplier_id') as observed_supplier_id,
    json_extract_string(claim.value, '$.field') as claim_field,
    json_extract_string(claim.value, '$.value') as claim_value,
    json_extract_string(claim.value, '$.confidence') as claim_confidence,
    json_extract_string(claim.value, '$.extraction_method') as extraction_method,
    try_cast(json_extract_string(claim.value, '$.retrieved_at') as timestamptz) as claim_retrieved_at,
    json_extract_string(claim.value, '$.source.source_id') as source_id,
    json_extract_string(claim.value, '$.source.artifact_type') as artifact_type,
    json_extract_string(claim.value, '$.source.title') as source_title,
    json_extract_string(claim.value, '$.source.url') as source_url,
    json_extract_string(claim.value, '$.source.mime_hint') as mime_hint,
    try_cast(json_extract_string(claim.value, '$.source.page') as integer) as source_page,
    try_cast(json_extract_string(claim.value, '$.source.row') as integer) as source_row,
    json_extract_string(claim.value, '$.source.text_span') as source_text_span
from {{ ref('stg_ingestion_events') }} as event,
    json_each(event.payload, '$.source_claims') as claim
